apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-api
  template:
    metadata:
      labels:
        app: speedtest-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: speedtest-api
          image: k8s101registry.azurecr.io/speed-test-api:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: basePath
              value: /

---
kind: Service
apiVersion: v1
metadata:
  name: speedtest-api-service
spec:
  type: LoadBalancer
  selector:
    app: speedtest-api
  ports:
    - protocol: TCP
      port: 80

---

