apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: speedtest-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: speedtest-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: speedtest-api
          image: taeregistry.azurecr.io/speed-test-api:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: hostBasePath
              value: /

---

kind: Service
apiVersion: v1
metadata:
  name: speedtest-api-service
spec:
  type: LoadBalancer
  selector:
    app: speedtest-api
  ports:
  - protocol: TCP
    port: 80

---
